In [3]:
#Installinh numpy in AnaConda Jupyter 
conda install numpy


Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done



In [4]:
#Always import numpy
import numpy as np

In [5]:
#Crating a list
list1=[5,10,15,20,25,30]

Arr=np.array(list1)

In [6]:
type(Arr)

numpy.ndarray

In [8]:
#Arr.shape helps you in displaying the no of rows and colums
Arr.shape

(6,)

In [15]:
list2=[1,2,3,4]
list3=[5,6,7,8]
list4=[9,10,11,12]

Arr2=np.array([list2,list3,list4])

In [16]:
Arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
Arr2.shape

(3, 4)

In [20]:
#Arr.reshape helps you in reshaping the array
Arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
#Indexing

In [23]:
Arr3=np.array([2,4,6,8,10,12,14])

In [25]:
#for 1D array
Arr3[4]

10

In [26]:
#for 2D array
#->a[:,:]=All rows and all columns
Arr2[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
Arr2[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [29]:
arr=np.arange(0,10)#creates a array from 0-9

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.linspace(1,5,3)# to create a array of points in between 1-5 3 points

array([1., 3., 5.])

In [32]:
#copy function and broadcasting
arr[3:]=33

In [33]:
arr

array([ 0,  1,  2, 33, 33, 33, 33, 33, 33, 33])

In [34]:
arr1=arr.copy()
arr1[3:]=100
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [35]:
#Imp for EDA
val=2

In [39]:
arr1*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [38]:
arr1+4

array([  4,   5,   6, 104, 104, 104, 104, 104, 104, 104])

In [40]:
arr1[arr1<5.5]

array([0, 1, 2])

In [41]:
#np.ones creates all ones
arr3=np.ones(5)

In [42]:
arr3

array([1., 1., 1., 1., 1.])

In [43]:
#random distribution- selects the random values
np.random.rand(3,3)

array([[0.12494585, 0.28956711, 0.19044911],
       [0.94064875, 0.70778468, 0.17432173],
       [0.92646683, 0.92354915, 0.44113443]])

In [46]:
np.random.randint(0,10,8)#select 5 points between 0 and 10 of integer

array([6, 9, 4, 5, 0, 4, 9, 6])